image: bitnami/laravel

pipelines:
  default:
    - step:
        caches:
          - node
          - docker
          - composer
        script:
          - composer install
          - npm install node
          - ln -f -s .env.pipelines .env
          - php artisan migrate
          - npm install
          - npm run build
        services:
          - docker

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'laravel'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'laravel'
        MYSQL_PASSWORD: 'secret'
