image: bitnami/laravel

pipelines:
  default:
    - step:
        script:
          - cp .env.example .env
          - composer install
          - ln -f -s .env.pipelines .env
          - php artisan generate:key
          - php artisan migrate
          - npm install
          - npm run build

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'laravel'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'laravel'
        MYSQL_PASSWORD: 'secret'
